# Generated by Django 3.2.4 on 2021-07-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='reqid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
